//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3Eksamen2022.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class S3Eksamen2022Entities : DbContext
    {
        public S3Eksamen2022Entities()
            : base("name=S3Eksamen2022Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<Informants> Informants { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<Targets> Targets { get; set; }
    }
}
