//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3Eksamen2022.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Targets
    {
        public int Id { get; set; }
        public string GivenName { get; set; }
        public string FamilyName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Nationality { get; set; }
        public string HairColor { get; set; }
        public string EyeColor { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    }
}
